### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#10]
This is a popular feature on the existing site, we should be sure to port it. I believe TailwindCSS has something built in to make this easier :crossed_fingers:

**Comment by doomspork** [comment]
![image](https://user-images.githubusercontent.com/73386/110543812-033c8d00-80e8-11eb-8e5f-4a83acf1dcb1.png)

**Comment by kinson** [comment]
@doomspork do you mind if I take a stab at this? 

If not, where is this image from? I cloned the repo and spun up the web app but it is not there and the dark mode control on elixirschool.com looks different.

**Comment by doomspork** [comment]
Howdy @kinson _absolutely_ :heart: I would love the help :tada: 

I "photoshopped" the image as just an idea for how this could be done. I'm open to other suggestions :grin: 

@burden did bring up a good point that we should move the Locale menu somewhere else (we're also going to improve the responsiveness of the Lesson menu). This could take the place of that drop down.

**Comment by kinson** [comment]
Sweet, that's a great jumping off point!

I'll start by adding a new dark mode control next to the drop down and enabling a dark theme with Tailwind.

Once there is something to look at, if it still makes sense to move the drop down menu somewhere else I can do that.

Thanks for the quick reply and guidance here ✌🏼

**Comment by doomspork** [comment]
Very excited to see how you implement the dark mode. I'll be the first to tell you I'm not super well versed in the UI/UX side of things so this will be a learning experience for me :tada: 

Thanks so much for helping out :pray:

**Comment by kinson** [comment]
@doomspork it was a learning experience for me as well, but the pr is up for review now (#56)!

And glad to help 😄

**Comment by kinson** [comment]
@doomspork since I have some momentum now I think I'll work on another issue! Before I pick one, is there one that comes to mind that would make the most sense to work on next?

**Comment by kinson** [comment]
@doomspork unless there is something I missed, I think this issue can be closed!

**Comment by doomspork** [comment]
Sorry @kinson, I was on vacation last week (first time in 2 years 😌)!

The only real pressing priority UI wise (that I am currently aware of) is the responsiveness of the lesson menu but I think I can leverage my license for TailwindUI to find something that works without any of us having to invest too much time in that particular task.

I'm open to any thoughts you have!

**Comment by kinson** [comment]
@doomspork no worries at all, I hope it was a good break!

I am working on the conferences page (#51) right now. I can take a look at the responsiveness issue next if it still needs to be done.
