### ISSUE TITLE
Broken images in blog posts

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#100]
There are some blog posts where the images are not being properly rendered:

https://rocketvalidator.com/s/0bdee490-cff7-495a-95a3-40211cd2b5cd/i?search=Bad+value+“%7B%25+&page=1&non_doc=false

It complains about "Bad value “{% asset " and the images are broken. For example in https://beta.elixirschool.com/blog/live-view-with-channels

![Captura de pantalla 2021-07-25 a las 19 01 23](https://user-images.githubusercontent.com/2629/126907230-d2b4f5ed-772a-4589-8b7b-25209043af6f.png)

This doesn't happen in the main site, https://elixirschool.com/blog/live-view-with-channels so I guess these tags were only valid in Jekyll?

**Comment by doomspork** [comment]
_Most_ of this should be fix in the content branch. However, anyone adding new content is bound to add stuff that gets messed. We're going to want to work through all of the blogs once we're on the launchpad

**Comment by jaimeiniesta** [comment]
Alright, then I'll just mute those issues, we should review all the content before launch.
