### ISSUE TITLE
Beta site is down

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#108]
Hey https://beta.elixirschool.com/ is down...

**Comment by doomspork** [comment]
Yup! @kinson and I both looked and we're not really sure why. One of the recent merges seemed to kill the deploy. I am busy for most of the morning but will look over lunch.

**Comment by doomspork** [comment]
> Monitor is UP: School House ( https://beta.elixirschool.com ). It was down for 49 minutes and 53 seconds.

Magic...apparently

**Comment by jaimeiniesta** [comment]
Yay! Ngrok was also being super slow, maybe there was a temporary network megaissue somewhere.
