### ISSUE TITLE
External links should open a new window

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#137]
These homepage links should open a new window

![image](https://user-images.githubusercontent.com/73386/134753368-136a3402-c541-4aa4-a549-439de042b943.png)

**Comment by doomspork** [comment]
@burden @kinson either of you want to grab this?

**Comment by kinson** [comment]
@doomspork based on the [w3 standards](https://www.w3.org/TR/WCAG20-TECHS/G200.html), it is recommended from an accessibility perspective that links do not open new tabs or windows unless it is necessary.

Normally, I would add a `target="_blank"` to open links in new tabs as well, but if we want to focus on accessibility here maybe it's worth leaving them as is.

**Comment by doomspork** [comment]
Okay! TIL
