### ISSUE TITLE
Several English Basic, Advanced, Specifics, and Libraries Links Returning 404 Response.

### ISSUE THREAD

**Issue by BrooklinJazz** [elixirschool/school_house#141]
I noticed that many links on the main page of the site are returning a 404 response.

Here's a list of what I've found that is broken so far.

- https://elixirschool.com/en/lessons/basics/iex-helpers/
- https://elixirschool.com/en/lessons/advanced/escripts/
- https://elixirschool.com/en/lessons/advanced/otp-concurrency/
- https://elixirschool.com/en/lessons/advanced/otp-supervisors/
- https://elixirschool.com/en/lessons/advanced/otp-distribution/
- https://elixirschool.com/en/lessons/advanced/umbrella-projects/
- https://elixirschool.com/en/lessons/advanced/gen-stage/
- https://elixirschool.com/en/lessons/specifics/plug/
- https://elixirschool.com/en/lessons/specifics/eex/
- https://elixirschool.com/en/lessons/specifics/ets/
- https://elixirschool.com/en/lessons/specifics/mnesia/
- https://elixirschool.com/en/lessons/libraries/guardian/
- https://elixirschool.com/en/lessons/libraries/poolboy/
- https://elixirschool.com/en/lessons/libraries/distillery/
- https://elixirschool.com/en/lessons/libraries/stream-data/
- https://elixirschool.com/en/lessons/libraries/nimble-publisher/

I have not gone into other languages to see if they have the same problem. I've confirmed on Twitter that I'm not the only person experiencing this. https://twitter.com/BrooklinJMyers/status/1442245449046392838

Thank you so much for the awesome project, I love Elixir School. I haven't contributed to this project yet but will try to find out why this is happening when I have some time. 

Please let me know if I can help or improve this issue 🙏 First time here.

**Comment by kinson** [comment]
Thanks for reporting the issue @BrooklinJazz 🎉 - I can repro this as well.

If you remove the trailing slash do you still see the 404s (I do not)?

Of course, this isn't ideal, so I can take a look sometime this week at the cause of the issue and fix it, or if you want to take a stab at it let me know and I can try to point you in the right direction!

**Comment by kinson** [comment]
Whoops! I spoke too soon, it seems like some of these urls are structured slightly differently on the new site than the old site. For instance:

* https://elixirschool.com/en/lessons/basics/iex_helpers works but your link (https://elixirschool.com/en/lessons/basics/iex-helpers/) does not
* https://elixirschool.com/en/lessons/misc/poolboy works but your link (https://elixirschool.com/en/lessons/libraries/poolboy/) does not

While these are technically no longer pages on elixir school, we should add them to the redirects file to better handle the updated web page paths.

**Comment by BrooklinJazz** [comment]
Thank you @kinson!

I should mention in case it wasn't clear that I'm taken to these links by interacting with the website itself. So the current buttons take me to 404 requests.

I'm going to have a look and explore the codebase tonight :) Thank you!

**Comment by BrooklinJazz** [comment]
Upon further inspection, I think this was a caching issue because my main page looks like the old version. Opened elixirschools.com in incognito and everything works fine.

I'm writing up a PR to make sure that requests to old routes will redirect to the new ones so that old links and bookmarks don't have any issues.

**Comment by kinson** [comment]
I just verified each of the links in the issue and they are now redirecting as expected 🎊
