### ISSUE TITLE
XML sitemaps keep showing beta URLs

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#143]
https://elixirschool.com/sitemap_dark_mode.xml is including beta URLs:

```xml
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>https://beta.elixirschool.com/blog?ui=dark</loc>
  </url>
  <url>
    <loc>https://beta.elixirschool.com/privacy?ui=dark</loc>
  </url>
```

Similar for https://elixirschool.com/sitemap.xml - in this case, it's fine when I browse it (I'm in Spain), but Rocket Validator is also getting beta URLs (the scraper is in US).

Rocket Validator can't scrape the site, because the URLs are not in the same subdomain.

**Comment by jaimeiniesta** [comment]
Fixed! Thanks! 🚀

**Comment by doomspork** [comment]
@kinson is the MVP!

**Comment by kinson** [comment]
@jaimeiniesta good catch 😅 on that one
