### ISSUE TITLE
Resource loading issue

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/school_house#153]
The pages keeps trying to fetch an image, takes a while spinning but then fails. Here is the network result:

![Screenshot from 2021-10-03 18-48-20](https://user-images.githubusercontent.com/4966172/135761583-b1d5412f-bead-45e2-9c17-28153db2b071.png)

**Comment by kinson** [comment]
Thanks for reporting this! I'll create a pr to fix it and reach out to the author to approve the change (since it's related to his blog post).

**Comment by gemantzu** [comment]
:fire:

**Comment by kinson** [comment]
Fixed in https://github.com/elixirschool/elixirschool/pull/2669
