### ISSUE TITLE
The whole page should be localized

### ISSUE THREAD

**Issue by gemantzu** [elixirschool/school_house#154]
Right now, when you click on a translation on the top right, nothing changes besides the lessons' content itself.

What should change:
- lessons content
- lessons links in navbar
- starting page for each language should show up instead of always English
- navbar itself

**Comment by doomspork** [comment]
@gemantzu have you checked the code itself to see if it has gettext setup? We may just need to generate the localses?

**Comment by gemantzu** [comment]
no, doing so right now. The translation landing page though and the navbar localized lessons should not be gettext specific, I think it's code specific

**Comment by gemantzu** [comment]
Hm, I see that the navbar lesson titles are coming from gettext, AND the setup for the english version is there. Are we good with this option, or do you think we should rely on the lessons themselves to provide these titles?

**Comment by Camilotk** [comment]
I noticed it also! Its a minor thing since all lessons are translated but cause a bad impression for people who won't speak english since looks like the localization won't work in first glance.

![Screenshot(3)](https://user-images.githubusercontent.com/30880723/150533110-97ea09bd-9d4e-4ef2-a6ef-09a024e87bbb.png)

**Comment by tenshikiri** [comment]
#192 should do the trick!

**Comment by tenshikiri** [comment]
All that's needed now for all languages, is to have [each .po file in here](https://github.com/elixirschool/school_house/tree/main/priv/gettext) translated accordingly.

**Comment by kinson** [comment]
Closing out this issue since it was added in #192, feel free to re-open or create a new issue if there is more work, but since we have the ground work laid for full-page translations I think we can close it safely.
