### ISSUE TITLE
Suggestion for translation_missing page

### ISSUE THREAD

**Issue by sujinleeme** [elixirschool/school_house#180]
Happy Halloween eve. 🎃

As a Korean speaker myself, I'd like to contribute translation when I read Korean doc but it was not smooth to find the specific folder/file in the elixirschool repo. What about adding words of encouragement and connecting location where they can check in the GitHub repo directly?

For example, https://elixirschool.com/no/lessons/ecto/associations has no translation file. In case, we can add a link to go parent directory. ; https://github.com/elixirschool/elixirschool/tree/master/lessons/no

This is just an idea.

<img width="806" alt="Screenshot 2021-10-29 at 13 11 37" src="https://user-images.githubusercontent.com/6011401/139425341-09f5a19b-15d3-49f2-bc27-c187a44cdda6.png">

**Comment by doomspork** [comment]
@sujinleeme this is a _great_ idea! I'm sorry I missed this notification 😰 Do you have any interest in implementing this?

**Comment by sujinleeme** [comment]
@doomspork  I'd like to help. 💜

**Comment by doomspork** [comment]
Hooray! Thank you @sujinleeme 💜

**Comment by lubien** [comment]
Ig that's ok I'd like to take a stab on this issue

**Comment by doomspork** [comment]
Please do @lubien!

**Comment by lubien** [comment]
I think this can be closed? 👀
