### ISSUE TITLE
/lessons/ecto/basics/ is Page Not Found

### ISSUE THREAD

**Issue by yellowsman** [elixirschool/school_house#186]
Hi :)

https://elixirschool.com/en/lessons/ecto/basics/ is showed "Page Not Found".

I think this url needs to be fixed because it's a hit for DuckDuckGo and Bing searches.
https://duckduckgo.com/?q=elixirschool+ecto+basic&t=h_&ia=web

thanks.

**Comment by kinson** [comment]
@yellowsman thanks for raising this issue. I am unable to reproduce this issue myself (the page loads from GitHub and Google/Duck Duck Go). 

Do you mind trying a different browser? And then if that still doesn't work I would be curious what your browser network log looks like when you attempt to load the page.

**Comment by yellowsman** [comment]
@kinson 
I see. I'm sorry.
I displayed it in a different browser and it didn't give me an error, thanks!
I'll consult the Vivaldi browser forum!

**Comment by kinson** [comment]
No problem, thanks for following up! If you can, try to clear any cache/saved data related to elixirschool.com on the affected browser. The site switched IPs/hosts so if your browser is caching the old host then that could explain your issue.
