### ISSUE TITLE
Table of contents does not properly handle sections with `` in the name

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#2]
There's a few pages where the section header is an inline code fragment like `if`, these are not being handled by the table of contents code correctly because they become nested tags.

I think there's 2 options here:

1. We update all of those lessons to no longer make use of the `` in section headers. This also unifies the styling of all the table of contents and headers.
2. Work through the parsing logic to support them. The most challenge example if the section "`if` and `unless`"

**Comment by doomspork** [comment]
@elixirschool/developers any thoughts on this one? I'm leaning towards #1 which would also clean up the how headers and table of contents look between pages as many don't use code snippets.

**Comment by jaimeiniesta** [comment]
I'm not sure as I don't have examples for these, but option number 1 sounds good to me, 👍  for unifying.

**Comment by doomspork** [comment]
I've addressed this by removing the `` from all the lesson headers.
