### ISSUE TITLE
Trigger HTML / A11Y validation on deploys

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#21]
Related to #20 I think we could also add a webhook to notify of deploys on Rocket Validator. This way, an automatic report looking for HTML / Accessibility issues can be run. Here's more info, but basically we just need to `POST` to an URL that contains the trigger:

https://docs.rocketvalidator.com/deploy-hooks/

I can set this up if that sounds like a good idea. All I need to know are the main URLs to validate (production, staging...)

**Comment by doomspork** [comment]
@jaimeiniesta I think this would be rad! Right now this is running at beta.elixirschool.com. 

Do you know if they offer any plans for open source or educational tools? If not that may be okay. Since folks have been asking I've decided to open up accepting donations which will be used for services like this, accessibility improvements, translations, and other community focused initiatives.

**Comment by jaimeiniesta** [comment]
That's great! Yes, I know _they_ offer free plans for open source because (I thought you already knew) I'm the guy behind Rocket Validator 🚀 😆 

I'm already giving free accounts for other open source projects, like [Docusaurus](https://github.com/facebook/docusaurus) - you can see that in return they've included a mention at the bottom of the README - which is very nice but not required.

OK, so if you want access, just let me know the email you'll be using to sign up in RV and I'll give you Pro access for free. You can email me at **jaime AT rocketvalidator.com** and I'll set you up (this is open for anyone interested around here as long as the accounts are used for open source).

**Comment by doomspork** [comment]
I didn't put two and two together :facepalm: I'll send you an email this evening. Thanks so much @jaimeiniesta. Happy to include a README note and find a way to call this out on the site as well :grin:

**Comment by doomspork** [comment]
Oh boy! This is going to highlight my weak HTML/CSS game :laughing:
 
https://rocketvalidator.com/s/f31eb8c9-2e6f-4a89-830c-5377559cedd7

**Comment by jaimeiniesta** [comment]
Hah! Most sites out there have a *lot* more issues than that, no worries 😄 

I'll send some PRs to help fix some of them (and also, some issues should just be muted).

**Comment by doomspork** [comment]
I setup a monthly schedule + deploy hook :tada:

**Comment by jaimeiniesta** [comment]
That's great!

Are you using a webhook for the deploys? What integration are you using to launch it?

**Comment by doomspork** [comment]
I went the simple route for now and used the Heroku Webhooks addon. I set the schedule up to be 25 pages. I figure so long as there are shared issues between them there isn't much point in running it on a larger segment. We can work up to that :grin:

**Comment by jaimeiniesta** [comment]
That's a wise decision. I prefer to start small, validating a small amount of web pages, and then increase the number when you consider the site free of issues, but you can still monitor for new issues.
