### ISSUE TITLE
Broken links to port 80

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#22]
I've run a Rocket Validator report on the beta site, and the crawler has found some broken links, on pages that use the `80` port:

https://rocketvalidator.com/s/5a71bc62-29c6-4e85-9ce5-2af0513f1976

Not sure yet if these are direct links or redirections, any idea?

**Comment by jaimeiniesta** [comment]
Ah yes, definitely those links are on the front page:

![Captura de pantalla 2021-04-15 a las 12 12 54](https://user-images.githubusercontent.com/2629/114853284-eaf51780-9de3-11eb-82e4-ef67d09328fa.png)

**Comment by jaimeiniesta** [comment]
I still think this PR is needed, to fully configure the app to run in Heroku (if we're going to use Heroku, that's what I think was planned).

**Comment by doomspork** [comment]
I'm good with merging if we can remove the SSL redirect until I can see about disable Cloudflare.

**Comment by doomspork** [comment]
This is currently deploying. We should be good to check if this fixed the issue in ~10 minutes.

**Comment by doomspork** [comment]
Nice work @jaimeiniesta, this can be closed. 

Closed via #23.
