### ISSUE TITLE
Homepage stats on Elixir adoption and community

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#55]
To help drive home the awesomeness of Elixir, the community, and the ecosystem as a whole stats would be great. Some ideas:

- Number of conferences
- Number of podcasts
- Number of translations on Elixir School
- Number of companies (see: elixir-companies.com)
- Number of countries with an Elixir presence (meetups/conference/etc)
- Number of Hex packages

**Comment by SophieDeBenedetto** [comment]
❤️ LOVE this idea! Maybe number of Elixir courses? Between Udemy, Pluralsight, learn-elixir.dev, pragmatic studio, etc. there are quite a few out there now.
