### ISSUE TITLE
Road to Launch

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#59]
I'm going to use this issue to outline what remains to get this iteration of Elixir School live 🚀 

__Must Have__ 
1. Update Lessons menu to be more responsive. cc @burden 
1. ~Move gettext into external repo to keep translation materials together. Note: The downside here is keeping them updated. I will tackle this.~
1. ~Automated deploys for changes to both repositories #20~
1. Announcement blog post

__Nice to Have__ 
1. Add code examples to homepage and Why Elixir? pages #32 
1. ~Blog RSS feed. We have this currently so it would be a loss of functionality for a short time. I could see this being move to Must Have. #54~
1. ~Sitemap.xml #62~
1. Expand on the Why Elixir and homepage copy
1. Document project

**Comment by kinson** [comment]
@doomspork I am taking a stab at the first item on the must have list right now as a part of #9 . If you'd rather `@burden` (avoiding re-notifying them) tackle it, I help with something else on this list!

**Comment by doomspork** [comment]
@kinson have at it! I think Mike is pretty swamped with work lately so I'm not sure what his availability is.

**Comment by doomspork** [comment]
@gemantzu as a translator what are your thoughts on 2:

> Move gettext into external repo to keep translation materials together. Note: The downside here is keeping them updated. I will tackle this.

Right now the gettext for Phoenix is in this repo and includes some content that needs translation. Everything else lives in the original repository.

**Comment by gemantzu** [comment]
I would say that if we won't have them inside the elixirschool lessons repo, don't move them, a third repo will overcomplicate things for translators. And would there be any benefit from that? when will you know when to force an update in the application if a gettext translation has changed? is there a way to automate this as well?

**Comment by doomspork** [comment]
I'm suggesting moving them from https://github.com/elixirschool/school_house into https://github.com/elixirschool/elixirschool, alongside the lessons/posts.

**Comment by doomspork** [comment]
Merges of new content to elixirschool/elixirschool will now trigger a deploy here. There's an issue with the deploy (separate of that) that I need to resolve.

@kinson I just realized we're both in Denver 🎉  We should grab coffee one day, my treat 😁

**Comment by kinson** [comment]
@doomspork great idea! I am not sure what your preferred method of chat is, but feel free to send me an email at swilkinsonhunter@gmail.com and we can find a time & place that works!

**Comment by doomspork** [comment]
Email sent 🚀 

I felt super motivated this weekend so I've been working my way through the list. I've got a PR open for sitemap and rss mix tasks #64 if someone wants to take a peek. There's also #60 which I updated to reply on a Makefile instead of mix task so it was easier to use in Docker pre-compile.

**Comment by doomspork** [comment]
I've started on the blog post for this announcement 👍
