### ISSUE TITLE
Populate Remaining Empty Links

### ISSUE THREAD

**Issue by kinson** [elixirschool/school_house#73]
There are several links on the home page that have no corresponding page on the website. @doomspork should we create new pages for each of them?

Here are the ones I've noticed - I may be missing a few:

**Header:**
- [x] Get Involved
- [x] Support

**Footer:**
- [x] Blog > Announcements
- [x] Blog > Today I Learned
- [x] Blog > Reviews
- [x] Project > Contributors
- [x] Project > Get Involved
- [x] Project > Support

**Comment by doomspork** [comment]
> Get Involved

Yes we need a new page here. I don't 💯  know what I wanted to capture here but essentially a few CTAs for different opportunities to contribute:

1. Translations. This could include steps to how to translate or link out to another new page depending on how much content we have for that.
2. New content. This could direct people to the Issues on the content repo maybe with a `new-lesson` label filter?
3. Blog posts.
4. ??

> Support

This is going to be on me and may not be doable by launch. I am exploring some legal things here. 

 > Blog > Announcements
 > Blog > Today I Learned
 > Blog > Reviews 
 
 For these we need to implement the functionality to filter blog posts by tags and then link to those 3 pre-filtered.
 
> Project > Contributors

**Comment by kinson** [comment]
@doomspork should we remove the support button for now then?

**Comment by doomspork** [comment]
@kinson that works for me 🙌

**Comment by kinson** [comment]
Thanks for sorting this out! I created #74 & #75 & #76 to address the remaining pieces of work.
