### ISSUE TITLE
Enable Filtering for Blog Posts

### ISSUE THREAD

**Issue by kinson** [elixirschool/school_house#75]
Right now in the footer of the website there are three links that should link to a list of blog posts filtered by their associated tag. We need to implement the filtering logic and update the following links:

* Blog > Announcements
* Blog > Today I Learned
* Blog > Reviews

Split from #73

**Comment by sbinlondon** [comment]
Hi there, is this issue still up for grabs?

**Comment by kinson** [comment]
Totally! And don't hesitate to follow up if you have any questions or need clarification!

**Comment by kinson** [comment]
Implemented in #125 🎊
