### ISSUE TITLE
HTML / Accessibility validation

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#77]
Hello!

As we talked in https://github.com/elixirschool/school_house/issues/35 we're using Rocket Validator to check for HTML and Accessibility issues in the new site for Elixir School.

I've set up a weekly schedule to run site-wide reports, and the new domain stats feature (now in beta) gives the latest reports run for that domain, and some nice stats showing the evolution in the number of issues and check coverage.

Here's the direct link to the latest stats and reports for that domain:

https://rocketvalidator.com/domains/elixirschool.com?auth=171c6160-f0a2-49d9-b83f-065c15c8a072

@doomspork feel free to replace this with your own shared link, so that we get the data from reports in your account, which I believe should be our main reference.

**Comment by jaimeiniesta** [comment]
I've muted some issues, for example those related to `phx-` attributes (required by Phoenix), and those related to `x-` attributes, needed for Alpine:

https://rocketvalidator.com/domains/beta.elixirschool.com?tab=mutings&date=&auth=e536facf-2cba-4288-ba45-3e7b95addcf8

If there are more issues like this that we should mute (as are out of our scope, so we won't fix them) please let me know!

**Comment by doomspork** [comment]
Thank you so much @jaimeiniesta! I am going to start going through the new features you released later this week, super excited for this!

**Comment by jaimeiniesta** [comment]
No problem, I'll be eating my own dog food and using Rocket Validator to find and fix issues in School House. So expect some PRs :)

By the way if anyone is interested in getting free account for open source just ping me at jaime AT rocketvalidator DOT com and I'll set you up.

My recommended flow is using ngrok to open a local tunnel into your dev machine so you can validate while you develop:

https://docs.rocketvalidator.com/how-to-validate-your-local-server/

**Comment by doomspork** [comment]
@kinson was asking me the other day how he could test changes locally 🎉 

@jaimeiniesta just so you're aware I'm trying to aim for us to launch this new site in the next 2 weeks. I'm afraid with my upcoming schedule (buying a house, moving, big work project) that if we don't do it now, it may not come to be for many moons.

**Comment by jaimeiniesta** [comment]
@kinson ping me with your email and I'll set a free account for you so you can test changes locally.

@doomspork tight schedules are great for focusing :D

**Comment by kinson** [comment]
@jaimeiniesta my email is swilkinsonhunter@gmail.com , thanks for adding me and thanks for finding and fixing all of these issues!

**Comment by jaimeiniesta** [comment]
Hey @kinson I'll send you an email with instructions!

We're making good progress! Just by fixing some of the HTML issues, take a look at the issue density graphs:

## [HTML issue density](https://rocketvalidator.com/domains/beta.elixirschool.com?tab=html&date=&auth=e536facf-2cba-4288-ba45-3e7b95addcf8)

![Captura de pantalla 2021-07-22 a las 20 09 43](https://user-images.githubusercontent.com/2629/126688387-47aa18e8-091e-40ce-bfd1-f1fd27edb7e3.png)

## [A11Y issue density](https://rocketvalidator.com/domains/beta.elixirschool.com?tab=a11y&date=&auth=e536facf-2cba-4288-ba45-3e7b95addcf8)

![Captura de pantalla 2021-07-22 a las 20 12 33](https://user-images.githubusercontent.com/2629/126688528-eedd1bba-bf96-4e66-bd9b-2c7e74270a6a.png)

Let's crush those issues!

**Comment by doomspork** [comment]
Wow! That's really awesome. I would very much like to highlight the work you both have done with this A11Y stuff, I don't feel as though it is widely known or understood.

Do you think there's merit in writing a short blog post on Elixir School just about these efforts? While it may not directly relate to Elixir it's important for the health of the community and the internet 🎉 

@jaimeiniesta the URL you provided: will that always be static? I'd like to include a link to this report in the footer (if possible) and on the contributing page that @kinson is taking a stab at. That is, in addition to a call out on the homepage to yourself and AppSignal for the support. If you have thoughts on the latter I'm all ears.

**Comment by jaimeiniesta** [comment]
Hey @doomspork I'm happy to help!

Yes, that URL is going to be static - as long as I keep it shared, which I plan to do. I mean, it's a "shared link" on the new Domain Stats feature. You may want to set your own but as you're busy, I'm happy with keeping mine.

I'll be happy to write a short blog post explaining how we're crushing those issues. I can explain our setup, and maybe also mention what we did to fix the site (based on the PR history).

**Comment by kinson** [comment]
@jaimeiniesta I am trying to understand how muting rules work on RV. Is a muting rule tied to a specific domain or to a specific run by a particular user?

For instance, if I wanted to mute a rule like [this](https://rocketvalidator.com/s/0bdee490-cff7-495a-95a3-40211cd2b5cd/p/4678413/i?search=Attribute+%E2%80%9Ccontent%E2%80%9D+not+allowed+on+element+%E2%80%9Cmeta%E2%80%9D+at+this+point.&non_doc=false) that is a part of Phoenix, would I run a report from my account and then add the muting via the muting page on RV along with the ones you've already added? Thanks in advance and feel free to link me to a documentation page that I may be missing!

**Comment by jaimeiniesta** [comment]
@kinson each user has his own muting rules. So the rules you define apply only to your reports. We should agree on what rules to apply.

A muting rule is formed by a URL match and a message match. For example these are the rules I've defined in my account

https://rocketvalidator.com/domains/beta.elixirschool.com?tab=mutings&date=&auth=

In that example there are 3 rules, the first one means: _mute anything on URLs containing "elixirschool.com" and "Attribute “@click"_

The URL match can be something as broad as the domain or a more specific URL part, like "elixirschool.com/blog" for example.

Muted issues still exist in the reports, but are muted - they don't show up until you explicitly disable muted visibility.

More info found here:

https://docs.rocketvalidator.com/muting/

**Comment by kinson** [comment]
Thanks for the explanation, do you have a proposal for how we should set the muting rules for the project? Perhaps a json or yaml file with the muting phrases listed for the domain.

**Comment by jaimeiniesta** [comment]
I'm writing a quick guide explaining how we use Rocket Validator in this project, as a markdown file. I think we can include them in that document by now.

**Comment by jaimeiniesta** [comment]
OK so we're almost at [0 HTML issues](https://rocketvalidator.com/domains/beta.elixirschool.com?tab=html&date=&auth=e536facf-2cba-4288-ba45-3e7b95addcf8) (pending some content fixes) so I'll be focusing now in the accessibility checks!

**Comment by jaimeiniesta** [comment]
Now that we're using the main domain, I've updated the shared domain stats, this is the new URL (I've also edited it in the previous comments)

https://rocketvalidator.com/domains/elixirschool.com?auth=171c6160-f0a2-49d9-b83f-065c15c8a072

**Comment by jaimeiniesta** [comment]
🎉  🎉  🎉  🚀    Good job everyone! We've achieved a 96% score on HTML checking for the site. This means that for the 1,017 URLs checked, only 4% of them have any issue - and they're only warnings:

![Captura de pantalla 2021-11-02 a las 18 34 51](https://user-images.githubusercontent.com/2629/139916587-7ef05e68-0f96-46ac-9940-4babccb7ea90.png)

Here's the link to the latest report. I'll open issues to fix the remaining warnings:

https://rocketvalidator.com/s/3b30de02-419d-4c3a-ac45-b055680a8f3b

...and after that, we can continue with accessibility checks - we're at 47%, not bad at all!

**Comment by jaimeiniesta** [comment]
The next biggest HTML issue is this one - it's on the other repo as it's related to content:

https://github.com/elixirschool/elixirschool/issues/2711

**Comment by jaimeiniesta** [comment]
Yay, look at the [HTML issues chart for the domain](https://rocketvalidator.com/domains/elixirschool.com/html?auth=171c6160-f0a2-49d9-b83f-065c15c8a072) !!!

![Captura de pantalla 2021-11-02 a las 21 47 44](https://user-images.githubusercontent.com/2629/139949336-d5afa676-2dc3-4227-8f3d-0969ee256670.png)

**Comment by jaimeiniesta** [comment]
![Captura de pantalla 2021-11-05 a las 18 16 02](https://user-images.githubusercontent.com/2629/140551632-a02f62ca-f32b-4055-9f96-f8c5078e9e2d.png)

Only [1 issue left](https://github.com/elixirschool/elixirschool/issues/2712) to get 100% valid HTML!

🚀 🚀 🚀
