### ISSUE TITLE
Elixir version?

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#79]
I think we should set a required Elixir version, currently in mix.exs it says 1.7.0 but that's quite old, is there any reason not to use 1.12?

Maybe we can add a `.tool-versions` file like it's done in asdf, or maybe it's enough with specifying it in the README?

**Comment by doomspork** [comment]
This is a great idea. I'm 💯  on board!

**Comment by jaimeiniesta** [comment]
Alright I'll send a PR to upgrade to 1.12
