### ISSUE TITLE
Locale menu should validate current locale

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#87]
https://beta.elixirschool.com/klingon makes it think like we're supporting that language, but we're not :D

![Captura de pantalla 2021-07-23 a las 11 29 38](https://user-images.githubusercontent.com/2629/126763370-51e4350a-c3ed-42a9-b841-4e4e85483747.png)

**Comment by kinson** [comment]
😲 good catch! If you are not already working on a fix, I'll take a look this weekend. @doomspork my assumption is that we would want to redirect the user to `/` if they try to navigate to a locale that does not exist.

**Comment by jaimeiniesta** [comment]
@kinson please go ahead with this, I didn't plan on fixing it yet. Both redirecting to `/` or defaulting to the `en` locale sound good to me.
