### ISSUE TITLE
Dark mode white flash

### ISSUE THREAD

**Issue by jaimeiniesta** [elixirschool/school_house#88]
How can we avoid that white flash when browsing in dark mode?

I'm not sure how the dark mode is activated, but it looks like each request renders the pages in white mode and then it's switched to dark, which is quite confusing.

**Comment by kinson** [comment]
@jaimeiniesta ill take a look at this too. I was able to eliminate the white flash on initial implementation, but it seems to be back again about half the time the page is reloaded.

**Comment by kinson** [comment]
Closed by #89
