### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by doomspork** [elixirschool/school_house#9]
The focus has been just the desktop experience so far. We need to revisit all of the markup to improve the tablet and phone experience.

**Comment by doomspork** [comment]
@burden you're the master of responsiveness. Would you be willing to take a peek at this and throw up PRs for any improvements you see?

**Comment by doomspork** [comment]
Most of the newer UI I've used has come from TailwindUI which is far better at responsiveness than I. Unfortunately, the header and lesson menu _is not_ and that seems to be one of the bigger issues. I can take a look this weekend to see if there's a better alternative to use in the interest of improving the responsiveness without investing too much time in custom styles and components.

**Comment by kinson** [comment]
@doomspork is there any more changes that should be made before this issue gets closed?

**Comment by doomspork** [comment]
I think we can close this for now @kinson and create specific tickets for issues that come up.

By the way @kinson this is the last run of Rocket Validator: https://rocketvalidator.com/s/e835d94c-5a08-46f2-bb79-a6ebaa65d2dc
